// Code generated by protoc-gen-ecode v0.7, DO NOT EDIT.
// source: web_ecode.proto

package v1

import (
	"gitlab.com/firerocksg/xy3-kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// WebErrCode ecode
var (
	GetWarZoneListFailed     = ecode.New(60001)
	WarZoneProhibitModify    = ecode.New(60002)
	AddWarZoneFailed         = ecode.New(60003)
	GetServerListFailed      = ecode.New(60004)
	ServerInfoProhibitModify = ecode.New(60005)
	AddServerInfoFailed      = ecode.New(60006)
)
