// 定义项目 API 的 proto 文件 可以同时描述 gRPC 和 HTTP API
// protobuf 文件参考:
//  - https://developers.google.com/protocol-buffers/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: account/account.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package v1

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockType int32

const (
	LockType_LT_Invalid LockType = 0
	LockType_LT_Lock    LockType = 1 // 封禁
	LockType_LT_UnLock  LockType = 2 // 解封
)

// Enum value maps for LockType.
var (
	LockType_name = map[int32]string{
		0: "LT_Invalid",
		1: "LT_Lock",
		2: "LT_UnLock",
	}
	LockType_value = map[string]int32{
		"LT_Invalid": 0,
		"LT_Lock":    1,
		"LT_UnLock":  2,
	}
)

func (x LockType) Enum() *LockType {
	p := new(LockType)
	*p = x
	return p
}

func (x LockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockType) Descriptor() protoreflect.EnumDescriptor {
	return file_account_account_proto_enumTypes[0].Descriptor()
}

func (LockType) Type() protoreflect.EnumType {
	return &file_account_account_proto_enumTypes[0]
}

func (x LockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockType.Descriptor instead.
func (LockType) EnumDescriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{0}
}

// 查询封号列表类型
type LockListType int32

const (
	LockListType_LLT_Invalid LockListType = 0
	LockListType_LLT_Account LockListType = 1 // 账号
	LockListType_LLT_UserId  LockListType = 2 // 玩家角色
)

// Enum value maps for LockListType.
var (
	LockListType_name = map[int32]string{
		0: "LLT_Invalid",
		1: "LLT_Account",
		2: "LLT_UserId",
	}
	LockListType_value = map[string]int32{
		"LLT_Invalid": 0,
		"LLT_Account": 1,
		"LLT_UserId":  2,
	}
)

func (x LockListType) Enum() *LockListType {
	p := new(LockListType)
	*p = x
	return p
}

func (x LockListType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockListType) Descriptor() protoreflect.EnumDescriptor {
	return file_account_account_proto_enumTypes[1].Descriptor()
}

func (LockListType) Type() protoreflect.EnumType {
	return &file_account_account_proto_enumTypes[1]
}

func (x LockListType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockListType.Descriptor instead.
func (LockListType) EnumDescriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{1}
}

// 登录方式
type LoginType int32

const (
	LoginType_LT          LoginType = 0 // 无效
	LoginType_LT_Guest    LoginType = 1 //游客登录
	LoginType_LT_Email    LoginType = 2 //邮箱登录
	LoginType_LT_Apple    LoginType = 3 //苹果登录
	LoginType_LT_Facebook LoginType = 4 //facebook登录
	LoginType_LT_Google   LoginType = 5 //google登录
	LoginType_LT_Phone    LoginType = 6 //手机登录
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "LT",
		1: "LT_Guest",
		2: "LT_Email",
		3: "LT_Apple",
		4: "LT_Facebook",
		5: "LT_Google",
		6: "LT_Phone",
	}
	LoginType_value = map[string]int32{
		"LT":          0,
		"LT_Guest":    1,
		"LT_Email":    2,
		"LT_Apple":    3,
		"LT_Facebook": 4,
		"LT_Google":   5,
		"LT_Phone":    6,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_account_account_proto_enumTypes[2].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_account_account_proto_enumTypes[2]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{2}
}

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AccountRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID     int32  `protobuf:"varint,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	UserID       int64  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Level        int32  `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	HeadID       int32  `protobuf:"varint,5,opt,name=HeadID,proto3" json:"HeadID,omitempty"`
	FrameID      int32  `protobuf:"varint,6,opt,name=FrameID,proto3" json:"FrameID,omitempty"`
	Sex          int32  `protobuf:"varint,7,opt,name=Sex,proto3" json:"Sex,omitempty"`
	LogoutTime   int64  `protobuf:"varint,8,opt,name=LogoutTime,proto3" json:"LogoutTime,omitempty"`
	DisabledTime int64  `protobuf:"varint,9,opt,name=DisabledTime,proto3" json:"DisabledTime,omitempty"` //封号到该时间戳
}

func (x *AccountRole) Reset() {
	*x = AccountRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRole) ProtoMessage() {}

func (x *AccountRole) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRole.ProtoReflect.Descriptor instead.
func (*AccountRole) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountRole) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *AccountRole) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AccountRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountRole) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AccountRole) GetHeadID() int32 {
	if x != nil {
		return x.HeadID
	}
	return 0
}

func (x *AccountRole) GetFrameID() int32 {
	if x != nil {
		return x.FrameID
	}
	return 0
}

func (x *AccountRole) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *AccountRole) GetLogoutTime() int64 {
	if x != nil {
		return x.LogoutTime
	}
	return 0
}

func (x *AccountRole) GetDisabledTime() int64 {
	if x != nil {
		return x.DisabledTime
	}
	return 0
}

type ServerPlayerNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID  int32 `protobuf:"varint,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	PlayerNum int32 `protobuf:"varint,2,opt,name=PlayerNum,proto3" json:"PlayerNum,omitempty"`
}

func (x *ServerPlayerNum) Reset() {
	*x = ServerPlayerNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerPlayerNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPlayerNum) ProtoMessage() {}

func (x *ServerPlayerNum) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPlayerNum.ProtoReflect.Descriptor instead.
func (*ServerPlayerNum) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *ServerPlayerNum) GetServerID() int32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *ServerPlayerNum) GetPlayerNum() int32 {
	if x != nil {
		return x.PlayerNum
	}
	return 0
}

// 拉取SDK-uuid对应的角色列表
type AccountRoleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SDKAccountId string `protobuf:"bytes,1,opt,name=SDKAccountId,proto3" json:"SDKAccountId,omitempty"`
	SdkToken     string `protobuf:"bytes,2,opt,name=SdkToken,proto3" json:"SdkToken,omitempty"`
	PlatformID   int32  `protobuf:"varint,3,opt,name=PlatformID,proto3" json:"PlatformID,omitempty"` //平台 0 默认 100-火元素内部测试
	ChannelID    int32  `protobuf:"varint,4,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`   //渠道ID 0 默认渠道 100-火元素内部测试
}

func (x *AccountRoleListReq) Reset() {
	*x = AccountRoleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleListReq) ProtoMessage() {}

func (x *AccountRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleListReq.ProtoReflect.Descriptor instead.
func (*AccountRoleListReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *AccountRoleListReq) GetSDKAccountId() string {
	if x != nil {
		return x.SDKAccountId
	}
	return ""
}

func (x *AccountRoleListReq) GetSdkToken() string {
	if x != nil {
		return x.SdkToken
	}
	return ""
}

func (x *AccountRoleListReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *AccountRoleListReq) GetChannelID() int32 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

type AccountRoleListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List                []*AccountRole     `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	AccountToken        string             `protobuf:"bytes,2,opt,name=AccountToken,proto3" json:"AccountToken,omitempty"`
	ServerPlayerNumList []*ServerPlayerNum `protobuf:"bytes,3,rep,name=ServerPlayerNumList,proto3" json:"ServerPlayerNumList,omitempty"`
	DeleteTime          int64              `protobuf:"varint,4,opt,name=DeleteTime,proto3" json:"DeleteTime,omitempty"` //账户注销时间戳 0 表示不限制， 其他表示截至时间戳 账户将会注销 请用户核查,并取消
}

func (x *AccountRoleListRsp) Reset() {
	*x = AccountRoleListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRoleListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleListRsp) ProtoMessage() {}

func (x *AccountRoleListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleListRsp.ProtoReflect.Descriptor instead.
func (*AccountRoleListRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{5}
}

func (x *AccountRoleListRsp) GetList() []*AccountRole {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AccountRoleListRsp) GetAccountToken() string {
	if x != nil {
		return x.AccountToken
	}
	return ""
}

func (x *AccountRoleListRsp) GetServerPlayerNumList() []*ServerPlayerNum {
	if x != nil {
		return x.ServerPlayerNumList
	}
	return nil
}

func (x *AccountRoleListRsp) GetDeleteTime() int64 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

type UserDisableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	DisabledTime int64  `protobuf:"varint,2,opt,name=DisabledTime,proto3" json:"DisabledTime,omitempty"` //从现在起封号到DisabledTime时间点
	Tips         string `protobuf:"bytes,3,opt,name=Tips,proto3" json:"Tips,omitempty"`                  //封号理由
}

func (x *UserDisableReq) Reset() {
	*x = UserDisableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDisableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisableReq) ProtoMessage() {}

func (x *UserDisableReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisableReq.ProtoReflect.Descriptor instead.
func (*UserDisableReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{6}
}

func (x *UserDisableReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserDisableReq) GetDisabledTime() int64 {
	if x != nil {
		return x.DisabledTime
	}
	return 0
}

func (x *UserDisableReq) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

type UserDisableRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *UserDisableRsp) Reset() {
	*x = UserDisableRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDisableRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisableRsp) ProtoMessage() {}

func (x *UserDisableRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisableRsp.ProtoReflect.Descriptor instead.
func (*UserDisableRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{7}
}

func (x *UserDisableRsp) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

// 封号请求
type LockAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`       // 账号
	UserId  []int64  `protobuf:"varint,2,rep,packed,name=UserId,proto3" json:"UserId,omitempty"` // 玩家id   Account || UserId 只用传入一个即可
	EndTime int64    `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`      // 截至时间
	Type    LockType `protobuf:"varint,4,opt,name=Type,proto3,enum=account.LockType" json:"Type,omitempty"`
}

func (x *LockAccountReq) Reset() {
	*x = LockAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAccountReq) ProtoMessage() {}

func (x *LockAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAccountReq.ProtoReflect.Descriptor instead.
func (*LockAccountReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{8}
}

func (x *LockAccountReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LockAccountReq) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *LockAccountReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *LockAccountReq) GetType() LockType {
	if x != nil {
		return x.Type
	}
	return LockType_LT_Invalid
}

type LockAccountRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockAccountRsp) Reset() {
	*x = LockAccountRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAccountRsp) ProtoMessage() {}

func (x *LockAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAccountRsp.ProtoReflect.Descriptor instead.
func (*LockAccountRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{9}
}

// 封号记录查询
type LockListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    LockListType `protobuf:"varint,1,opt,name=Type,proto3,enum=account.LockListType" json:"Type,omitempty"`
	Offset  int32        `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit   int32        `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`    // 最大返回100条
	UserId  int64        `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`  // 用于指定 userid查询
	Account string       `protobuf:"bytes,5,opt,name=Account,proto3" json:"Account,omitempty"` // 用于指定 账户 查询
}

func (x *LockListReq) Reset() {
	*x = LockListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockListReq) ProtoMessage() {}

func (x *LockListReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockListReq.ProtoReflect.Descriptor instead.
func (*LockListReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{10}
}

func (x *LockListReq) GetType() LockListType {
	if x != nil {
		return x.Type
	}
	return LockListType_LLT_Invalid
}

func (x *LockListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LockListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LockListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockListReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type LockItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`            // 兼容UserId 和Account
	EndTime int64  `protobuf:"varint,2,opt,name=EndTime,proto3" json:"EndTime,omitempty"` // 请求方主动判断 endTime <> time.Now()?  是否处于被封号中
}

func (x *LockItem) Reset() {
	*x = LockItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockItem) ProtoMessage() {}

func (x *LockItem) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockItem.ProtoReflect.Descriptor instead.
func (*LockItem) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{11}
}

func (x *LockItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LockItem) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 封号记录查询
type LockListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List       []*LockItem `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	TotalCount int64       `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
}

func (x *LockListRsp) Reset() {
	*x = LockListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockListRsp) ProtoMessage() {}

func (x *LockListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockListRsp.ProtoReflect.Descriptor instead.
func (*LockListRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{12}
}

func (x *LockListRsp) GetList() []*LockItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *LockListRsp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 踢玩家线下
type KickPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`    // 当account不为空时， 踢账号下所有玩家
	PlayerId int64  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"` // 指定userid 只踢 该玩家
}

func (x *KickPlayerReq) Reset() {
	*x = KickPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerReq) ProtoMessage() {}

func (x *KickPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerReq.ProtoReflect.Descriptor instead.
func (*KickPlayerReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{13}
}

func (x *KickPlayerReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *KickPlayerReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type KickPlayerRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KickPlayerRsp) Reset() {
	*x = KickPlayerRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickPlayerRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRsp) ProtoMessage() {}

func (x *KickPlayerRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRsp.ProtoReflect.Descriptor instead.
func (*KickPlayerRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{14}
}

// 获取玩家详情信息
type GetPlayerInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId   []int64 `protobuf:"varint,1,rep,packed,name=PlayerId,proto3" json:"PlayerId,omitempty"` // 玩家id  最多查询十个
	PlayerName string  `protobuf:"bytes,2,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`     // 玩家名称  两者发送一个即可， 优先玩家id
}

func (x *GetPlayerInfoReq) Reset() {
	*x = GetPlayerInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoReq) ProtoMessage() {}

func (x *GetPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{15}
}

func (x *GetPlayerInfoReq) GetPlayerId() []int64 {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *GetPlayerInfoReq) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// 玩家详情
type GetPlayerInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Player `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *GetPlayerInfoRsp) Reset() {
	*x = GetPlayerInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoRsp) ProtoMessage() {}

func (x *GetPlayerInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoRsp.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{16}
}

func (x *GetPlayerInfoRsp) GetList() []*Player {
	if x != nil {
		return x.List
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OS            int32     `protobuf:"varint,1,opt,name=OS,proto3" json:"OS,omitempty"`                                      // 平台
	WarZone       int32     `protobuf:"varint,2,opt,name=WarZone,proto3" json:"WarZone,omitempty"`                            // 战区
	Server        int32     `protobuf:"varint,3,opt,name=Server,proto3" json:"Server,omitempty"`                              // 服务器id
	Account       string    `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`                             // 账户
	LoginType     LoginType `protobuf:"varint,5,opt,name=LoginType,proto3,enum=account.LoginType" json:"LoginType,omitempty"` // 登录方式  (暂定)
	PlayerId      int64     `protobuf:"varint,6,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`                          // 玩家id
	PlayerName    string    `protobuf:"bytes,7,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`                       // 玩家名称
	Mobile        string    `protobuf:"bytes,8,opt,name=Mobile,proto3" json:"Mobile,omitempty"`                               // 手机号 				(暂定)
	Level         int32     `protobuf:"varint,9,opt,name=Level,proto3" json:"Level,omitempty"`                                // 等级
	VipLevel      int32     `protobuf:"varint,10,opt,name=VipLevel,proto3" json:"VipLevel,omitempty"`                         // vip等级			(暂定)
	Recharge      int32     `protobuf:"varint,11,opt,name=Recharge,proto3" json:"Recharge,omitempty"`                         // 总充值				(暂定)
	RegTime       int64     `protobuf:"varint,12,opt,name=RegTime,proto3" json:"RegTime,omitempty"`                           // 注册时间
	LastLoginTime int64     `protobuf:"varint,13,opt,name=LastLoginTime,proto3" json:"LastLoginTime,omitempty"`               // 最有一次登录
	LastLoginIp   string    `protobuf:"bytes,14,opt,name=LastLoginIp,proto3" json:"LastLoginIp,omitempty"`                    // 最后一次登录ip
	Online        bool      `protobuf:"varint,15,opt,name=Online,proto3" json:"Online,omitempty"`                             // 是否在线
	LockTime      int64     `protobuf:"varint,16,opt,name=LockTime,proto3" json:"LockTime,omitempty"`                         // 封号截至时间
	Email         string    `protobuf:"bytes,17,opt,name=Email,proto3" json:"Email,omitempty"`                                // 邮件
	Imei          string    `protobuf:"bytes,18,opt,name=Imei,proto3" json:"Imei,omitempty"`                                  //
	Apple         string    `protobuf:"bytes,19,opt,name=Apple,proto3" json:"Apple,omitempty"`                                //
	Facebook      string    `protobuf:"bytes,20,opt,name=Facebook,proto3" json:"Facebook,omitempty"`                          //
	Google        string    `protobuf:"bytes,21,opt,name=Google,proto3" json:"Google,omitempty"`                              //
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{17}
}

func (x *Player) GetOS() int32 {
	if x != nil {
		return x.OS
	}
	return 0
}

func (x *Player) GetWarZone() int32 {
	if x != nil {
		return x.WarZone
	}
	return 0
}

func (x *Player) GetServer() int32 {
	if x != nil {
		return x.Server
	}
	return 0
}

func (x *Player) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Player) GetLoginType() LoginType {
	if x != nil {
		return x.LoginType
	}
	return LoginType_LT
}

func (x *Player) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Player) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *Player) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *Player) GetRecharge() int32 {
	if x != nil {
		return x.Recharge
	}
	return 0
}

func (x *Player) GetRegTime() int64 {
	if x != nil {
		return x.RegTime
	}
	return 0
}

func (x *Player) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *Player) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *Player) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Player) GetLockTime() int64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *Player) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Player) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *Player) GetApple() string {
	if x != nil {
		return x.Apple
	}
	return ""
}

func (x *Player) GetFacebook() string {
	if x != nil {
		return x.Facebook
	}
	return ""
}

func (x *Player) GetGoogle() string {
	if x != nil {
		return x.Google
	}
	return ""
}

// 获取玩家仙人信息
type GetPlayerHeroInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"` // 玩家id
}

func (x *GetPlayerHeroInfoReq) Reset() {
	*x = GetPlayerHeroInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerHeroInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerHeroInfoReq) ProtoMessage() {}

func (x *GetPlayerHeroInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerHeroInfoReq.ProtoReflect.Descriptor instead.
func (*GetPlayerHeroInfoReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlayerHeroInfoReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type HeroInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`               // 仙人id
	Quality   int32 `protobuf:"varint,2,opt,name=Quality,proto3" json:"Quality,omitempty"`     // 品质
	Star      int32 `protobuf:"varint,3,opt,name=Star,proto3" json:"Star,omitempty"`           // 星级
	Fragments int32 `protobuf:"varint,4,opt,name=Fragments,proto3" json:"Fragments,omitempty"` // 仙人碎片数量
	Awaken    int32 `protobuf:"varint,5,opt,name=Awaken,proto3" json:"Awaken,omitempty"`       // 觉醒次数
}

func (x *HeroInfo) Reset() {
	*x = HeroInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroInfo) ProtoMessage() {}

func (x *HeroInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroInfo.ProtoReflect.Descriptor instead.
func (*HeroInfo) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{19}
}

func (x *HeroInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HeroInfo) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *HeroInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *HeroInfo) GetFragments() int32 {
	if x != nil {
		return x.Fragments
	}
	return 0
}

func (x *HeroInfo) GetAwaken() int32 {
	if x != nil {
		return x.Awaken
	}
	return 0
}

// 玩家仙人详情
type GetPlayerHeroInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*HeroInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *GetPlayerHeroInfoRsp) Reset() {
	*x = GetPlayerHeroInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_account_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerHeroInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerHeroInfoRsp) ProtoMessage() {}

func (x *GetPlayerHeroInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerHeroInfoRsp.ProtoReflect.Descriptor instead.
func (*GetPlayerHeroInfoRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{20}
}

func (x *GetPlayerHeroInfoRsp) GetList() []*HeroInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_account_account_proto protoreflect.FileDescriptor

var file_account_account_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x1a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x67,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x43, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x23, 0xf2, 0xde, 0x1f, 0x1f, 0x66,
	0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x09, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x25, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0b, 0xea, 0xde, 0x1f, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xf3, 0x01, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x49, 0x44,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4b,
	0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x92, 0x01, 0x0a, 0x12,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x44, 0x4b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x44, 0x4b, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x64, 0x6b, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x64, 0x6b, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44,
	0x22, 0xce, 0x01, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x4a, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x13, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x60, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x69, 0x70, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x83, 0x01,
	0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x73, 0x70, 0x22, 0x98, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x4c, 0x6f,
	0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x34, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x4c, 0x6f,
	0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x45, 0x0a, 0x0d,
	0x4b, 0x69, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x73, 0x70, 0x22, 0x4e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xc2, 0x04,
	0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x53, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x53, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x61, 0x72, 0x5a,
	0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x57, 0x61, 0x72, 0x5a, 0x6f,
	0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x56, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x56, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x67, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x52, 0x65, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4c,
	0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6d, 0x65, 0x69, 0x18, 0x12, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x49, 0x6d, 0x65, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c,
	0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x46, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x46, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48,
	0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x08, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x77, 0x61, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x41, 0x77, 0x61, 0x6b, 0x65, 0x6e, 0x22, 0x3d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x25,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x36, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x54, 0x5f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x54, 0x5f, 0x4c, 0x6f, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x4c, 0x54, 0x5f, 0x55, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x10, 0x02, 0x2a, 0x40, 0x0a,
	0x0c, 0x4c, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x4c, 0x4c, 0x54, 0x5f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x4c, 0x4c, 0x54, 0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x4c, 0x4c, 0x54, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x10, 0x02, 0x2a,
	0x6b, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x4c, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x54, 0x5f, 0x47, 0x75, 0x65, 0x73, 0x74,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x54, 0x5f, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x54, 0x5f, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x4c, 0x54, 0x5f, 0x46, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x10, 0x04, 0x12,
	0x0d, 0x0a, 0x09, 0x4c, 0x54, 0x5f, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x05, 0x12, 0x0c,
	0x0a, 0x08, 0x4c, 0x54, 0x5f, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x10, 0x06, 0x42, 0x1a, 0xc8, 0xe1,
	0x1e, 0x00, 0x5a, 0x14, 0x78, 0x79, 0x33, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_account_proto_rawDescOnce sync.Once
	file_account_account_proto_rawDescData = file_account_account_proto_rawDesc
)

func file_account_account_proto_rawDescGZIP() []byte {
	file_account_account_proto_rawDescOnce.Do(func() {
		file_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_account_proto_rawDescData)
	})
	return file_account_account_proto_rawDescData
}

var file_account_account_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_account_account_proto_goTypes = []interface{}{
	(LockType)(0),                // 0: account.LockType
	(LockListType)(0),            // 1: account.LockListType
	(LoginType)(0),               // 2: account.LoginType
	(*HelloReq)(nil),             // 3: account.HelloReq
	(*HelloResp)(nil),            // 4: account.HelloResp
	(*AccountRole)(nil),          // 5: account.AccountRole
	(*ServerPlayerNum)(nil),      // 6: account.ServerPlayerNum
	(*AccountRoleListReq)(nil),   // 7: account.AccountRoleListReq
	(*AccountRoleListRsp)(nil),   // 8: account.AccountRoleListRsp
	(*UserDisableReq)(nil),       // 9: account.UserDisableReq
	(*UserDisableRsp)(nil),       // 10: account.UserDisableRsp
	(*LockAccountReq)(nil),       // 11: account.LockAccountReq
	(*LockAccountRsp)(nil),       // 12: account.LockAccountRsp
	(*LockListReq)(nil),          // 13: account.LockListReq
	(*LockItem)(nil),             // 14: account.LockItem
	(*LockListRsp)(nil),          // 15: account.LockListRsp
	(*KickPlayerReq)(nil),        // 16: account.KickPlayerReq
	(*KickPlayerRsp)(nil),        // 17: account.KickPlayerRsp
	(*GetPlayerInfoReq)(nil),     // 18: account.GetPlayerInfoReq
	(*GetPlayerInfoRsp)(nil),     // 19: account.GetPlayerInfoRsp
	(*Player)(nil),               // 20: account.Player
	(*GetPlayerHeroInfoReq)(nil), // 21: account.GetPlayerHeroInfoReq
	(*HeroInfo)(nil),             // 22: account.HeroInfo
	(*GetPlayerHeroInfoRsp)(nil), // 23: account.GetPlayerHeroInfoRsp
}
var file_account_account_proto_depIdxs = []int32{
	5,  // 0: account.AccountRoleListRsp.List:type_name -> account.AccountRole
	6,  // 1: account.AccountRoleListRsp.ServerPlayerNumList:type_name -> account.ServerPlayerNum
	0,  // 2: account.LockAccountReq.Type:type_name -> account.LockType
	1,  // 3: account.LockListReq.Type:type_name -> account.LockListType
	14, // 4: account.LockListRsp.List:type_name -> account.LockItem
	20, // 5: account.GetPlayerInfoRsp.List:type_name -> account.Player
	2,  // 6: account.Player.LoginType:type_name -> account.LoginType
	22, // 7: account.GetPlayerHeroInfoRsp.List:type_name -> account.HeroInfo
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_account_account_proto_init() }
func file_account_account_proto_init() {
	if File_account_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerPlayerNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRoleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRoleListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDisableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDisableRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockAccountRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickPlayerRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerHeroInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_account_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerHeroInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_account_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_account_proto_goTypes,
		DependencyIndexes: file_account_account_proto_depIdxs,
		EnumInfos:         file_account_account_proto_enumTypes,
		MessageInfos:      file_account_account_proto_msgTypes,
	}.Build()
	File_account_account_proto = out.File
	file_account_account_proto_rawDesc = nil
	file_account_account_proto_goTypes = nil
	file_account_account_proto_depIdxs = nil
}
